### PR TITLE
Update to cqlsh 5.0.1

### PR DESCRIPTION
**Pull request by spiside**
Updates to cqlsh to 5.0.1 which is the most recent release of cqlsh. 

Status: **Requesting Merge**
## Changes
- Updated cqlsh executable file to 5.0.1
- Modified cqlshlib folder with the updated files

### CODE REVIEW

**Comment by scalp42** [comment]
@amussey any chance to merge?

**Comment by spiside** [comment]
Hey @scalp42!

I currently have a maintained fork that you can install from if you need to in the meantime.

**Comment by scalp42** [comment]
@spiside indeed, using your master branch, thanks :smile:

**Comment by spiside** [comment]
@scalp42 I would recommend using the v5.0.2 tagged version instead of the master branch. I'll try to keep it updated as more cqlsh releases come along.

**Comment by scalp42** [comment]
Great thanks again @spiside :+1:

**Comment by amussey** [comment]
@scalp42: my sincere apologies for the delayed reply.  I'll merge this in.

@spiside: thanks for maintaining that fork!  Would you have any interest in taking over the project on [pypi](https://pypi.python.org/pypi/cqlsh)?  As you can tell by the disrepair this repo has fallen into, I am not actively updating for new releases of cqlsh (I've moved to another company and am no longer actively working with Cassandra).

**Comment by spiside** [comment]
@amussey Sure, I wouldn't mind taking over the project. My username on pypi is the same as Github's

**Comment by scalp42** [comment]
@spiside using your branch `v5.0.2` I'm running into this error:

```
    ---- Begin output of /usr/local/bin/cqlsh --cqlversion 3.3.1 -u cassandra -p cassandra -f /opt/gearzero/migrations/gz-db/cassandra/cassandra_create-authdb.cql gz-dev1.docker.service.consul ----
    STDOUT:
    STDERR: Traceback (most recent call last):
      File "/usr/local/bin/cqlsh", line 111, in <module>
        from cassandra.cluster import Cluster, PagedResult
    ImportError: cannot import name PagedResult
    ---- End output of /usr/local/bin/cqlsh --cqlversion 3.3.1 -u cassandra -p cassandra -f /opt/gearzero/migrations/gz-db/cassandra/cassandra_create-authdb.cql gz-dev1.docker.service.consul ----
    Ran /usr/local/bin/cqlsh --cqlversion 3.3.1 -u cassandra -p cassandra -f /opt/gearzero/migrations/gz-db/cassandra/cassandra_create-authdb.cql gz-dev1.docker.service.consul returned 1
```

Do you happen to know why by any chance ?

**Comment by scalp42** [comment]
@spiside appears to be the update of the cassandra-driver:

```
cassandra-driver==2.7.2
```

vs

```
Collecting cassandra-driver (from cqlsh==5.0.2)
  Downloading cassandra-driver-3.0.0.tar.gz (186kB)
```

**Comment by spiside** [comment]
@scalp42 Glad you were able to get that to work! Thanks for letting me know.

**Pull request merged**
